-- =═══════════════════════════════════════════════
-- SUPABASE SCHEMA: CATEGORIES & SUBCATEGORIES
-- ════════════════════════════════════════════════

-- 1. DROP TABLES IF THEY EXIST (for clean migration)
-- DROP TABLE IF EXISTS public.subcategories CASCADE;
-- DROP TABLE IF EXISTS public.categories CASCADE;

-- 2. CREATE CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 3. CREATE SUBCATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 4. CREATE INDEXES ON SLUGS (for high-performance lookups)
CREATE INDEX IF NOT EXISTS categories_slug_idx ON public.categories (slug);
CREATE INDEX IF NOT EXISTS subcategories_slug_idx ON public.subcategories (slug);

-- 5. ENABLE ROW LEVEL SECURITY (RLS) - Supabase Security Best Practice
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- 6. CREATE RLS POLICIES
-- Drop existing policies first to ensure the script is fully idempotent
DROP POLICY IF EXISTS "Allow public read access to categories" ON public.categories;
DROP POLICY IF EXISTS "Allow public read access to subcategories" ON public.subcategories;
DROP POLICY IF EXISTS "Allow admin write access to categories" ON public.categories;
DROP POLICY IF EXISTS "Allow admin write access to subcategories" ON public.subcategories;

-- Public Read-Only Access
CREATE POLICY "Allow public read access to categories" 
ON public.categories FOR SELECT 
USING (true);

CREATE POLICY "Allow public read access to subcategories" 
ON public.subcategories FOR SELECT 
USING (true);

-- Authenticated Admin Full Access
CREATE POLICY "Allow admin write access to categories" 
ON public.categories FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow admin write access to subcategories" 
ON public.subcategories FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 7. SEED DATA: INSERT CATEGORIES (ON CONFLICT DO UPDATE for idempotency)
INSERT INTO public.categories (name, slug, description)
VALUES 
    ('Классическое нижнее белье', 'lingerie-classic', 'Премиальное классическое нижнее белье, бюстгальтеры, трусики и домашняя одежда'),
    ('Эротическое белье и одежда', 'lingerie-erotic', 'Чувственное эротическое белье, ролевые костюмы, портупеи и эротические аксессуары'),
    ('Игрушки для женщин', 'toys-women', 'Инновационные игрушки и стимуляторы для женского удовольствия и интимного здоровья'),
    ('Игрушки для мужчин', 'toys-men', 'Мастурбаторы, массажеры простаты и аксессуары для мужского здоровья и удовольствия'),
    ('Игрушки для пар', 'toys-couples', 'Девайсы и игры для совместного удовольствия, укрепляющие близость партнеров'),
    ('Анальные игрушки', 'toys-anal', 'Деликатные анальные пробки и виброшарики для ярких ощущений'),
    ('БДСМ и Фетиш', 'bdsm-fetish', 'Качели, фиксаторы и аксессуары для ролевых игр, связывания и доминирования'),
    ('Лубриканты и интимная косметика', 'lubricants-cosmetics', 'Премиальные смазки, возбуждающие средства, уходовая косметика и духи с феромонами')
ON CONFLICT (slug) 
DO UPDATE SET 
    name = EXCLUDED.name, 
    description = EXCLUDED.description;

-- 8. SEED DATA: INSERT SUBCATEGORIES
INSERT INTO public.subcategories (category_id, name, slug, description)
VALUES
    -- 1. Классическое нижнее белье (lingerie-classic)
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-classic'), 'Комплекты белья', 'lingerie-sets', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-classic'), 'Бюстгальтеры', 'bras', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-classic'), 'Трусики (базовые)', 'panties-basic', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-classic'), 'Домашние комплекты', 'loungewear', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-classic'), 'Боди, сорочки и халаты (классические)', 'classic-bodysuits-robes', NULL),

    -- 2. Эротическое белье и одежда (lingerie-erotic)
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Трусики с доступом', 'crotchless-panties', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Ролевые костюмы', 'roleplay-costumes', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Сетки (платья, боди)', 'mesh-bodysuits', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Эротические боди, сорочки и халаты', 'erotic-bodysuits-robes', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Чулки и колготки с доступом', 'crotchless-stockings', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Портупеи и пояса', 'harnesses-garter-belts', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Перчатки', 'erotic-gloves', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lingerie-erotic'), 'Съедобное белье', 'edible-lingerie', NULL),

    -- 3. Игрушки для женщин (toys-women)
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибраторы для клитора', 'clitoral-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибраторы для точки G', 'gspot-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибраторы-кролики', 'rabbit-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибропули', 'bullet-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибраторы с пультом', 'remote-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вибрационные трусики', 'vibrating-panties', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-women'), 'Вагинальные тренажеры', 'kegel-exercisers', NULL),

    -- 4. Игрушки для мужчин (toys-men)
    ((SELECT id FROM public.categories WHERE slug = 'toys-men'), 'Мужские мастурбаторы', 'male-masturbators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-men'), 'Массажеры простаты', 'prostate-massagers', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-men'), 'Эрекционные кольца', 'cock-rings', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-men'), 'Насадки', 'sleeves-extensions', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-men'), 'Многоразовые презервативы', 'reusable-condoms', NULL),

    -- 5. Игрушки для пар (toys-couples)
    ((SELECT id FROM public.categories WHERE slug = 'toys-couples'), 'Надеваемые вибромассажеры', 'wearable-couples-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-couples'), 'Вибраторы с дистанционным пультом', 'remote-couples-vibrators', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-couples'), 'Игры для двоих', 'games-couples', NULL),

    -- 6. Анальные игрушки (toys-anal)
    ((SELECT id FROM public.categories WHERE slug = 'toys-anal'), 'Анальные пробки', 'anal-plugs', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'toys-anal'), 'Анальные виброшарики', 'anal-beads', NULL),

    -- 7. БДСМ и Фетиш (bdsm-fetish)
    ((SELECT id FROM public.categories WHERE slug = 'bdsm-fetish'), 'Секс-качели', 'sex-swings', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'bdsm-fetish'), 'Аксессуары для фиксации и доминирования', 'restraints-dominance', NULL),

    -- 8. Лубриканты и интимная косметика (lubricants-cosmetics)
    ((SELECT id FROM public.categories WHERE slug = 'lubricants-cosmetics'), 'Смазки / Лубриканты', 'lubricants', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lubricants-cosmetics'), 'Возбуждающие средства', 'stimulants', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lubricants-cosmetics'), 'Сужающие кремы и спреи', 'tightening-creams', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lubricants-cosmetics'), 'Парфюмерия с феромонами', 'pheromone-perfumes', NULL),
    ((SELECT id FROM public.categories WHERE slug = 'lubricants-cosmetics'), 'Уходовая косметика', 'care-cosmetics', NULL)
ON CONFLICT (slug) 
DO UPDATE SET 
    name = EXCLUDED.name, 
    description = EXCLUDED.description;
