/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './index.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Stitch "Ethereal Noir" palette ──────────
        'background':                '#000000',
        'surface':                   '#000000',
        'surface-dim':               '#000000',
        'surface-bright':            '#3a3939',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#d0c5af',
        'inverse-surface':           '#e5e2e1',
        'inverse-on-surface':        '#313030',
        'outline':                   '#99907c',
        'outline-variant':           '#4d4635',
        'surface-tint':              '#e9c349',
        'primary':                   '#f2ca50',
        'on-primary':                '#3c2f00',
        'primary-container':         '#d4af37',
        'on-primary-container':      '#554300',
        'inverse-primary':           '#735c00',
        'secondary':                 '#c8c6c5',
        'on-secondary':              '#313030',
        'secondary-container':       '#474746',
        'on-secondary-container':    '#b7b5b4',
        'tertiary':                  '#bfcdff',
        'on-tertiary':               '#082b72',
        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'error-container':           '#93000a',
        'on-error-container':        '#ffdad6',
        'primary-fixed':             '#ffe088',
        'primary-fixed-dim':         '#e9c349',
        'on-primary-fixed':          '#241a00',
        'on-primary-fixed-variant':  '#574500',
        'on-background':             '#e5e2e1',
        'surface-variant':           '#353534',
        'graphite':                  '#2D2D2D',
        'copper-accent':             '#B87333',
        'pure-white':                '#FFFFFF',
        'muted-gold':                '#99813D',
      },
      borderRadius: {
        DEFAULT: '0',     // Sharp corners everywhere — brand rule
        sm:      '0',
        md:      '0',
        lg:      '0',
        xl:      '0',
        '2xl':   '0',
        full:    '9999px', // Only for color swatches
        card:    '12px',   // Rounded corners specifically for product cards
      },
      spacing: {
        'margin-mobile':  '24px',
        'margin-desktop': '80px',
        'section-gap':    '160px',
        'container-max':  '1440px',
        'gutter':         '32px',
      },
      fontFamily: {
        sans:            ['Montserrat', 'system-ui', 'sans-serif'],
        'display-lg':    ['Montserrat'],
        'headline-lg':   ['Montserrat'],
        'title-md':      ['Montserrat'],
        'body-lg':       ['Montserrat'],
        'body-md':       ['Montserrat'],
        'label-caps':    ['Montserrat'],
      },
      fontSize: {
        'display-lg':        ['64px',  { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '300' }],
        'headline-lg':       ['40px',  { lineHeight: '1.2',  letterSpacing: '0.05em',  fontWeight: '400' }],
        'headline-lg-mobile':['32px',  { lineHeight: '1.2',  letterSpacing: '0.05em',  fontWeight: '400' }],
        'title-md':          ['20px',  { lineHeight: '1.4',  letterSpacing: '0.1em',   fontWeight: '500' }],
        'body-lg':           ['18px',  { lineHeight: '1.6',  letterSpacing: '0.01em',  fontWeight: '300' }],
        'body-md':           ['16px',  { lineHeight: '1.6',  letterSpacing: '0.01em',  fontWeight: '300' }],
        'label-caps':        ['12px',  { lineHeight: '1.0',  letterSpacing: '0.2em',   fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      keyframes: {
        slideInRight: {
          from: { transform: 'translateX(100%)' },
          to:   { transform: 'translateX(0)' },
        },
        slideOutRight: {
          from: { transform: 'translateX(0)' },
          to:   { transform: 'translateX(100%)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'slide-in-right':  'slideInRight 0.35s cubic-bezier(0.25,0.46,0.45,0.94) both',
        'slide-out-right': 'slideOutRight 0.3s cubic-bezier(0.25,0.46,0.45,0.94) both',
        'fade-in':         'fadeIn 0.3s ease both',
        'fade-up':         'fadeUp 0.5s cubic-bezier(0.25,0.46,0.45,0.94) both',
      },
    },
  },
  plugins: [],
};
